name: Crawl Baseball News

on:
  schedule:
    - cron: '0 3 * * *' # 매일 한국 시간 오전 12시 실행 (UTC 3시)
  workflow_dispatch: # 수동 실행도 가능하도록 설정

jobs:
  crawl_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl

      - name: Run baseball news crawler
        run: |
          javac NaverSportsCrawler.java
          java NaverSportsCrawler

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add baseball_news.csv
          git commit -m "자동 크롤링: $(date +'%Y-%m-%d')"
          git push
        continue-on-error: true # 파일이 변경되지 않았으면 오류 방지