name: Crawl Baseball News

on:
  schedule:
    - cron: '0 3 * * *' # 매일 한국 시간 오전 12시 실행 (UTC 3시)
  workflow_dispatch: # 수동 실행 가능

jobs:
  crawl_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl

      - name: Download Jsoup Library
        run: |
          curl -L -o jsoup.jar https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.3/jsoup-1.14.3.jar

      - name: Compile Java with Jsoup
        run: |
          javac -cp .:jsoup.jar NaverSportsCrawler.java
          rm -f *.class  # 컴파일 후 .class 파일 삭제

      - name: Run Baseball News Crawler
        run: |
          java -cp .:jsoup.jar NaverSportsCrawler
          rm -f jsoup.jar  # 실행 후 jsoup.jar 삭제

      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A  # 변경된 모든 파일 추가
          git commit -m "자동 크롤링: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main || echo "No changes to push"
