name: Crawl Domestic Baseball News

on:
  schedule:
    - cron: '0 3 * * *'  # 매일 한국 시간 오전 12시 (UTC 3시)
  workflow_dispatch:     # 수동 실행 가능

jobs:
  crawl_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install curl
        run: sudo apt update && sudo apt install -y curl

      - name: Download org.json Library
        run: |
          curl -L -o json.jar https://repo1.maven.org/maven2/org/json/json/20230227/json-20230227.jar

      - name: Compile Java Code
        run: |
          javac -cp .:json.jar -d . NaverSportsNewsCrawler.java

      - name: Run Naver Sports News Crawler
        env:
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          KEYWORD: ${{ secrets.KEYWORD }}  # 또는 기본값("국내 야구 스포츠") 사용 가능
        run: |
          java -cp .:json.jar NaverSportsNewsCrawler
